'use client';
import {useState,useEffect,useRef} from 'react';
import {Search,MapPin,Globe2,ExternalLink,SlidersHorizontal,Check,BriefcaseBusiness,RotateCcw,Info,LoaderCircle} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Skeleton} from '@/components/ui/skeleton';
import {platforms,SearchInput,SearchResult,googleUrl,googleQuery,validateInput} from '@/lib/search';
import {boards} from '@/lib/registry';
const initial={keywords:'',location:'',remote:false,platforms:platforms.map(p=>p.id),expandTitles:true,searchDescriptions:false,includeUnknownRemote:false};
export default function Home(){
 const [form,setForm]=useState<SearchInput>(initial);const [submitted,setSubmitted]=useState<SearchInput|null>(null);const [result,setResult]=useState<SearchResult|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [validationError,setValidationError]=useState('');const [tab,setTab]=useState('live');const [sort,setSort]=useState('relevance');const [limit,setLimit]=useState(25);const request=useRef(0);
 const run=async(value:SearchInput)=>{let input:SearchInput;try{input=validateInput(value)}catch(e){setValidationError(e instanceof Error?e.message:'Check your search.');throw e}const id=++request.current;setForm(input);setSubmitted(input);setResult(null);setError('');setValidationError('');setBusy(true);setLimit(25);
  const q=new URLSearchParams({q:input.keywords,l:input.location,r:input.remote?'1':'0',p:input.platforms.join(','),a:input.expandTitles===false?'0':'1',d:input.searchDescriptions?'1':'0',u:input.includeUnknownRemote?'1':'0'});window.history.replaceState(null,'','?'+q);
  try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(20000)});const data=await r.json() as SearchResult & {error?:string};if(!r.ok)throw new Error(data.error);if(id===request.current)setResult(data);return data}catch(e){if(id===request.current)setError(e instanceof Error&&e.name==='TimeoutError'?'The job feeds took too long. Try again or use All ATS searches.':e instanceof Error?e.message:'Search failed. Please try again.');throw e}finally{if(id===request.current)setBusy(false)}
 };
 const runner=useRef(run);runner.current=run;
 useEffect(()=>{const q=new URLSearchParams(window.location.search);if(q.get('q')){void runner.current({keywords:q.get('q')!,location:q.get('l')??'',remote:q.get('r')==='1',platforms:q.get('p')?.split(',')??initial.platforms,expandTitles:q.get('a')!=='0',searchDescriptions:q.get('d')==='1',includeUnknownRemote:q.get('u')==='1'}).catch(()=>{})}},[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();void Promise.resolve(context.registerTool({name:'search_ats_jobs',title:'Search ATS jobs',description:'Search supported public company boards with optional title aliases, descriptions, and uncertain regional remote matches. Remote does not confirm work eligibility.',inputSchema:{type:'object',properties:{keywords:{type:'string',maxLength:180},location:{type:'string',maxLength:100},remote:{type:'boolean'},expandTitles:{type:'boolean',description:'Expand explicit title aliases; defaults to true.'},searchDescriptions:{type:'boolean',description:'Also match available description text; defaults to false.'},includeUnknownRemote:{type:'boolean',description:'Include remote regional or unspecified geography matches; defaults to false.'},platforms:{type:'array',items:{type:'string',enum:platforms.map(p=>p.id)},minItems:1}},required:['keywords','location','remote','platforms'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const data=await runner.current(validateInput(input));return {total:data.total,boards:data.boards,attempted:data.attempted,failed:data.failed,jobs:data.jobs.slice(0,10).map(j=>({title:j.title,company:j.company,url:j.url,match:j.match}))}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 const active=submitted??form;const jobs=[...(result?.jobs??[])].sort((a,b)=>sort==='company'?a.company.localeCompare(b.company):sort==='recent'?(Date.parse(b.published??'')||0)-(Date.parse(a.published??'')||0):0);
 const toggle=(id:string)=>setForm(f=>({...f,platforms:f.platforms.includes(id)?f.platforms.filter(x=>x!==id):[...f.platforms,id]}));
 const changed=submitted&&JSON.stringify(form)!==JSON.stringify(submitted);
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Search size={21}/></span>Job<span className="brand-light">Scape</span><span className="beta">BETA</span></a><div className="top-note">Direct from company job boards <span className="free-tag">Free to use</span></div></header>
  <main className="workspace">
   <section className="intro"><div className="eyebrow">THE JOB SEARCH, WITHOUT THE QUERY WRANGLING</div><h1>Find your next role.<br/><span>Go straight to the source.</span></h1><p>Search live company listings. Reach the major hiring platforms with the same search.</p></section>
   <form className="search-panel" onSubmit={e=>{e.preventDefault();void run(form).catch(()=>{})}}>
    <div className="search-fields"><label className="field"><span>Job title or keywords</span><div><Search size={20}/><input required maxLength={180} value={form.keywords} onChange={e=>setForm({...form,keywords:e.target.value})} placeholder="e.g. developer relations, community" aria-describedby="keyword-help"/></div></label><label className="field location"><span>Location</span><div><MapPin size={20}/><input maxLength={100} value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="City, country, or leave blank"/></div></label><button className="search-button" disabled={busy||!form.platforms.length} type="submit">{busy?<LoaderCircle className="spin" size={19}/>:<Search size={19}/>} {busy?'Searching':'Search jobs'}</button></div>
    <div className="search-bottom"><span id="keyword-help">Separate alternatives with a comma. Keywords match {form.searchDescriptions?'titles and available descriptions':'job titles'}.</span><label className="check-label"><Checkbox checked={form.remote} onCheckedChange={v=>setForm({...form,remote:v===true})}/>Remote only</label></div>
    <div className="search-options"><label className="check-label"><Checkbox checked={form.expandTitles!==false} onCheckedChange={v=>setForm({...form,expandTitles:v===true})}/>Include title aliases</label><label className="check-label"><Checkbox checked={form.searchDescriptions===true} onCheckedChange={v=>setForm({...form,searchDescriptions:v===true})}/>Search descriptions too</label>{form.remote&&form.location.trim()&&<label className="check-label"><Checkbox checked={form.includeUnknownRemote===true} onCheckedChange={v=>setForm({...form,includeUnknownRemote:v===true})}/>Include regional or unspecified remote locations</label>}<p>Aliases expand titles such as DevRel and SRE. Country searches include known cities and provider country fields. Work eligibility must be checked with the employer.</p></div>
    {validationError&&<p role="alert" className="search-validation">{validationError}</p>}
   </form>
   <div className="main-grid">
    <aside className="filters"><div className="filters-title"><SlidersHorizontal size={17}/><h2>Hiring platforms</h2></div><div className="select-actions"><button type="button" onClick={()=>setForm({...form,platforms:platforms.map(p=>p.id)})}>Select all</button><span>·</span><button type="button" onClick={()=>setForm({...form,platforms:[]})}>Clear</button></div><div className="provider-list">{platforms.map(p=><label className="provider" key={p.id}><Checkbox checked={form.platforms.includes(p.id)} onCheckedChange={()=>toggle(p.id)}/><span>{p.name}</span>{p.live&&<span className="live-mini">FEED</span>}</label>)}</div><p className="filter-foot"><Info size={16}/>FEED platforms support live results from selected company boards. Every platform supports a Google search.</p></aside>
    <section className="results-area"><Tabs value={tab} onValueChange={setTab}><div className="results-top"><TabsList className="results-tabs" variant="line"><TabsTrigger value="live">Live listings{result&&<span className="count">{result.total}</span>}</TabsTrigger><TabsTrigger value="all">All ATS searches<span className="count">{active.platforms.length}</span></TabsTrigger></TabsList>{submitted&&<button className="refresh" title="Rerun current search" disabled={busy} onClick={()=>void run(active).catch(()=>{})}><RotateCcw size={16}/><span>Refresh</span></button>}</div>
    {changed&&<p className="changed">Filters changed. Select Search jobs to update your results.</p>}
    <TabsContent value="live">
     {!submitted?<div className="welcome"><div className="welcome-icon"><BriefcaseBusiness size={28}/></div><h2>A shorter path to the right job.</h2><p>Start with a role and a location, or try a search below.</p><div className="examples">{['Developer relations','Community manager','Field marketing'].map(q=><button key={q} onClick={()=>void run({...form,keywords:q}).catch(()=>{})}><Search size={14}/>{q}</button>)}</div><div className="coverage"><span>{boards.length} registered company boards</span><span>3 live integrations</span><span>18 ATS search filters</span></div><p className="welcome-note">Live coverage focuses on tech, AI, and Web3 companies. Use All ATS searches to explore beyond these boards.</p></div>:
     busy?<div role="status" className="loading"><p><LoaderCircle size={18} className="spin"/>Checking company job boards…</p>{[1,2,3].map(i=><div className="loading-row" key={i}><Skeleton className="h-5 w-3/5"/><Skeleton className="mt-4 h-4 w-2/5"/></div>)}</div>:
     error?<div className="message error"><h2>We couldn’t load the feeds.</h2><p>{error}</p><button onClick={()=>setTab('all')}>Open all-ATS searches</button></div>:
     result&&<><div className="result-summary"><div><h2>{result.attempted>0&&result.boards===0?'Live feeds unavailable':<>{result.total} matching {result.total===1?'role':'roles'}</>}</h2><p>{result.scanned.toLocaleString()} listings checked across {result.boards} of {result.attempted} selected company boards</p></div><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort results"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="relevance">Job title</SelectItem><SelectItem value="company">Company</SelectItem><SelectItem value="recent">Latest date</SelectItem></SelectContent></Select></div>
      {result.failed.length>0&&<details className="feed-warning"><summary>{result.failed.length} company {result.failed.length===1?'feed was':'feeds were'} unavailable. {result.boards>0?'Results are partial.':'No live boards responded.'}</summary><p>{result.failed.join(', ')}. Try their ATS search below for broader coverage.</p></details>}
      {result.health&&result.health.length>0&&<details className="board-coverage"><summary>Company board coverage ({result.boards}/{result.attempted} responding)</summary><p>This is a finite employer registry. Counts describe accessible listings, not all jobs on an ATS.</p><ul>{result.health.map(board=><li key={board.platform+board.name}><a href={board.source} target="_blank" rel="noopener noreferrer">{board.name}</a><span>{board.status==='ok'?`${board.jobs.toLocaleString()} listings · ${board.cached?'Cached':'Fetched'}`:board.error??'Unavailable'} · Checked {new Date(board.checked).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span></li>)}</ul></details>}
      {active.searchDescriptions&&result.descriptions&&<p className="description-coverage">Descriptions available for {result.descriptions.available.toLocaleString()} of {result.scanned.toLocaleString()} checked listings. {result.descriptions.truncated>0&&`${result.descriptions.truncated.toLocaleString()} long descriptions searched up to 12,000 characters.`} Language and eligibility requirements are not inferred.</p>}
      {result.attempted===0&&<div className="message"><h2>These platforms support Google search.</h2><p>Select a FEED platform for live listings, or search the selected platforms below.</p><button onClick={()=>setTab('all')}>View ATS searches</button></div>}
      {result.attempted>0&&result.boards===0&&<div className="message error"><h2>We couldn’t load the selected feeds.</h2><p>No company boards responded. Try again or use the Google searches for these platforms.</p><button onClick={()=>setTab('all')}>Open all-ATS searches</button></div>}
      {result.boards>0&&jobs.length===0&&<div className="message"><h2>No matches in these company boards.</h2><p>Try a broader title, leave location blank, or search across all ATS platforms.</p><button onClick={()=>setTab('all')}>Search beyond these boards</button></div>}
      <div className="job-list">{jobs.slice(0,limit).map(j=><article className="job-card" key={j.id}><div className={'company-avatar '+j.platform}>{j.company.slice(0,1)}</div><div className="job-main"><div className="job-company">{j.company}<span>{platforms.find(p=>p.id===j.platform)?.name}</span></div><h3><a href={j.url} target="_blank" rel="noopener noreferrer">{j.title}</a></h3><div className="job-meta"><span><MapPin size={14}/>{j.location}</span>{j.remote&&<span className="remote-pill">Remote</span>}</div>{j.match&&<p className="match-reason">Matched {j.match.field}: “{j.match.term}”{j.match.alias?' (title alias)':''}</p>}{j.remote&&<p className={'eligibility '+(j.match?.location==='region'||j.match?.location==='unknown'?'uncertain':'')}>{j.match?.location==='region'?'Regional location; country eligibility unknown.':j.match?.location==='unknown'?'Remote location unspecified; country eligibility unknown.':active.location.trim()?`${active.location} matches a listed location; work eligibility not verified.`:'Remote work eligibility not verified.'}</p>}{(j.match?.snippet||j.description)&&<p className="job-description">{j.match?.snippet??(j.description.slice(0,160)+(j.description.length>160?'…':''))}</p>}<div className="job-dates">Checked {new Date(j.checked).toLocaleDateString('en-GB')}{j.published&&<span> · {j.dateKind==='updated'?'Updated':'Published'} {new Date(j.published).toLocaleDateString('en-GB')}</span>}</div></div><a className="open-job" href={j.url} target="_blank" rel="noopener noreferrer" aria-label={'View '+j.title+' at '+j.company}><ExternalLink size={17}/></a></article>)}</div>
      {jobs.length>limit&&<button className="load-more" onClick={()=>setLimit(l=>l+25)}>Show more roles ({jobs.length-limit} remaining)</button>}{result.truncated&&<p className="small-note">Showing the first 300 matches. Narrow your keywords to see more specific results.</p>}
      <div className="results-foot"><Info size={16}/><p>Feeds refresh at most every 10 minutes. “Updated” is an edit date, not a posting date. Remote listings may have country restrictions. Check eligibility on the company’s page.</p></div></>}
    </TabsContent>
    <TabsContent value="all"><div className="all-heading"><div><h2>One search. All your platforms.</h2><p>Google searches company application pages with your keywords and location. Results open in a new tab.</p></div>{active.keywords.trim()&&active.platforms.length>0&&<a className="google-all" href={googleUrl(active)} target="_blank" rel="noopener noreferrer"><Globe2 size={18}/>Search all selected</a>}</div>
     {!active.keywords.trim()?<div className="message"><h2>Add a role to get started.</h2><p>Your search links appear here as you type.</p></div>:active.platforms.length===0?<div className="message"><h2>Select a platform.</h2><p>Choose the hiring platforms you want to search.</p></div>:<><div className="ats-grid">{platforms.filter(p=>active.platforms.includes(p.id)).map((p,i)=><a key={p.id} className="ats-card" href={googleUrl(active,[p.id])} target="_blank" rel="noopener noreferrer"><span className={'ats-monogram tone-'+i%4}>{p.name.slice(0,1)}</span><div><h3>{p.name}</h3><p>{p.domains[0]}</p></div><ExternalLink size={16}/></a>)}</div><details className="query-details"><summary>See the generated search</summary><code>{googleQuery(active)}</code></details><p className="small-note">Search engines may miss unindexed pages or show closed roles. These are search links, not an exhaustive job index.</p></>}
    </TabsContent></Tabs></section>
   </div><footer><span>JobScape <span className="footer-separator">/</span> a direct route to company jobs</span><span>No account. No search API key.</span></footer>
  </main>
 </div>
}
