import assert from 'node:assert/strict';
import {sourceModule} from './load-source.mjs';
const {smartrecruiters}=await import(sourceModule('../lib/adapters/smartrecruiters.ts'));
const {matches}=await import(sourceModule('../lib/search.ts'));
const board={platform:'smartrecruiters',slug:'fixture',name:'Fixture',source:'https://example.test/careers'};
const posting=(id,extra={})=>({id:String(id),name:'Senior Developer Advocate',location:{city:'Berlin',country:'de',remote:true},releasedDate:'2026-09-01T00:00:00Z',visibility:'PUBLIC',...extra});
const context=json=>({json,descriptions:false,checked:'2026-10-02T00:00:00Z',remainingRequests:()=>48});
let pages=0;
const paged=await smartrecruiters.load(board,context(async url=>{pages++;const offset=Number(new URL(url).searchParams.get('offset'));return {offset,totalFound:250,content:Array.from({length:Math.min(100,250-offset)},(_,index)=>posting(offset+index+1))}}));
assert.equal(pages,3);assert.equal(paged.jobs.length,250);assert.equal(paged.complete,true);
const capped=await smartrecruiters.load(board,context(async url=>{const offset=Number(new URL(url).searchParams.get('offset'));return {offset,totalFound:999,content:Array.from({length:100},(_,index)=>posting(offset+index+1))}}));
assert.equal(capped.jobs.length,300);assert.equal(capped.complete,false);assert.match(capped.issues.join(' '),/Pagination capped/);
const fields=await smartrecruiters.load(board,context(async()=>({offset:0,totalFound:4,content:[posting(1),posting(2,{location:{city:'Berlin',country:'de',remote:true,hybrid:true}}),posting(3,{visibility:'INTERNAL'}),posting(4,{releasedDate:undefined,location:{city:'Paris',country:'fr',remote:false}})]})));
assert.equal(fields.jobs.length,3);assert.equal(fields.jobs[1].remote,false);assert.equal(fields.jobs[2].published,null);
assert.equal(matches(fields.jobs[0],{keywords:'DevRel',location:'Germany',remote:true,platforms:['smartrecruiters']}),true);
assert.equal(fields.jobs[0].dateKind,'published');assert.match(fields.jobs[0].url,/jobs.smartrecruiters.com/);
let details=0;const described=await smartrecruiters.load(board,{...context(async url=>{if(new URL(url).searchParams.has('offset'))return {offset:0,totalFound:8,content:Array.from({length:8},(_,index)=>posting(index+1))};details++;return {...posting(url.split('/').at(-1)),jobAd:{sections:{description:{text:'<p>Kubernetes &amp; APIs</p>'}}}}}),descriptions:true});
assert.equal(details,6);assert.equal(described.complete,false);assert.equal(described.jobs.filter(job=>job.description).length,6);assert.match(described.jobs[0].description,/Kubernetes & APIs/);
await assert.rejects(smartrecruiters.load(board,context(async()=>({content:[]}))),/pagination payload/);
console.log('SmartRecruiters checks passed: pagination, bounds, public-only jobs, fields, hybrid exclusion, aliases, and bounded real-detail shape.');
