import assert from 'node:assert/strict';
import {sourceModule} from './load-source.mjs';
const {workable}=await import(sourceModule('../lib/adapters/workable.ts'));
const {matches}=await import(sourceModule('../lib/search.ts'));
const board={platform:'workable',slug:'fixture',name:'Fixture',source:'https://example.test/careers'};
const job={shortcode:'ABC123',title:'Developer Advocate',state:'Berlin',city:'Berlin',country:'Germany',telecommuting:true,url:'https://apply.workable.com/j/ABC123',published_on:'2026-09-01',description:'<p>Kubernetes &amp; API tools</p>'};
const context=data=>({json:async()=>data,descriptions:false,checked:'2026-10-02T00:00:00Z',remainingRequests:()=>48});
const loaded=await workable.load(board,context({name:'Fixture',jobs:[job,{...job,shortcode:'HYBRID',title:'Developer Advocate (Hybrid)'},{...job,shortcode:'ON',workplace_type:'on_site'},{...job,shortcode:'DATE',published_on:undefined,created_at:'2026-01-01'},{...job,shortcode:'CLOSED',status:'closed'}]}));
assert.equal(loaded.jobs.length,4);assert.equal(loaded.jobs[0].remote,true);assert.equal(loaded.jobs[1].remote,false);assert.equal(loaded.jobs[2].remote,false);assert.equal(loaded.jobs[3].published,null);assert.equal(loaded.jobs[0].dateKind,'published');
assert.equal(matches(loaded.jobs[0],{keywords:'DevRel',location:'Germany',remote:true,platforms:['workable']}),true);
assert.match(loaded.jobs[0].description,/Kubernetes & API/);
const empty=await workable.load(board,context({name:'Fixture',jobs:[]}));assert.equal(empty.complete,true);assert.equal(empty.jobs.length,0);
await assert.rejects(workable.load(board,context({name:'Fixture'})),/payload/);
const pages=await workable.load(board,context({name:'Fixture',jobs:[job],next:'https://example.test/private-page'}));assert.equal(pages.complete,false);
const multi=await workable.load(board,context({name:'Fixture',jobs:[{...job,locations:[{countryCode:'DE',country:'Germany',city:'Berlin'},{countryCode:'US',country:'United States',city:'Boston'},{countryCode:'FR',country:'France',city:'Paris',hidden:true}]}]}));
assert.equal(multi.jobs[0].locations.length,2);assert.equal(matches(multi.jobs[0],{keywords:'DevRel',location:'USA',remote:true,platforms:['workable']}),true);
const repeated=await workable.load(board,context({name:'Fixture',jobs:[job,{...job,city:'Boston',state:'MA',country:'United States'}]}));
assert.equal(repeated.jobs.length,1);assert.equal(repeated.jobs[0].locations.length,2);assert.equal(matches(repeated.jobs[0],{keywords:'DevRel',location:'Germany',remote:true,platforms:['workable']}),true);assert.equal(matches(repeated.jobs[0],{keywords:'DevRel',location:'USA',remote:true,platforms:['workable']}),true);
console.log('Workable checks passed: public endpoint shape, geographic state, remote/hybrid/on-site, publication semantics, hidden locations, empty sources, and unexpected pagination.');
